services:
  couchdb-1.local:
    image: couch:latest
    volumes:
      - ${DB1_DATA:-./data}:/opt/couchdb/data
      - cht-credentials:/opt/couchdb/etc/local.d/
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-admin}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-pass}"
      - "COUCHDB_SECRET=${COUCHDB_SECRET}"
      - "COUCHDB_UUID=${COUCHDB_UUID}"
      - "SVC_NAME=${SVC1_NAME:-couchdb-1.local}"
      - "CLUSTER_PEER_IPS=${CLUSTER_PEER_IPS:-couchdb-2.local,couchdb-3.local}"
      - "COUCHDB_LOG_LEVEL=${COUCHDB_LOG_LEVEL:-info}"
    restart: always
    networks:
      - cht-net
    ports:
      - "5984:5984"

  api:
    image: public.ecr.aws/medic/cht-api:4.16.0
    restart: always
    expose:
      - "${API_PORT:-5988}"
    environment:
      - COUCH_URL=http://${COUCHDB_USER:-admin}:${COUCHDB_PASSWORD:-pass}@couchdb-1.local:5984/${COUCH_DB:-medic}
      - BUILDS_URL=${MARKET_URL_READ:-https://staging.dev.medicmobile.org}/${BUILDS_SERVER:-_couch/builds_4}
      - UPGRADE_SERVICE_URL=${UPGRADE_SERVICE_URL:-http://localhost:5100}
    logging:
      driver: "local"
      options:
        max-size: "${LOG_MAX_SIZE:-50m}"
        max-file: "${LOG_MAX_FILES:-20}"
    networks:
      - cht-net
    ports:
      - "5988:5988"
      - "80:5988"

networks:
  cht-net:
    name: ${CHT_NETWORK:-cht-net}
    external: true

volumes:
  cht-credentials:
  cht-ssl:
