services:
  couchdb-3.local:
    image: couch:latest
    volumes:
      - ${DB2_DATA:-./srv2}:/opt/couchdb/data
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-admin}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-pass}"
      - "COUCHDB_SECRET=${COUCHDB_SECRET}"
      - "COUCHDB_UUID=${COUCHDB_UUID}"
      - "SVC_NAME=${SVC2_NAME:-couchdb-3.local}"
      - "COUCHDB_LOG_LEVEL=${COUCHDB_LOG_LEVEL:-info}"
      - "COUCHDB_SYNC_ADMINS_NODE=${COUCHDB_SYNC_ADMINS_NODE:-couchdb-1.local}"
    logging:
      driver: "local"
      options:
        max-size: "${LOG_MAX_SIZE:-50m}"
        max-file: "${LOG_MAX_FILES:-20}"
    restart: always
    networks:
      cht-net:

networks:
  cht-net:
    name: ${CHT_NETWORK:-cht-net}
    external: true

volumes:
  cht-credentials:
  cht-ssl:
